import requests
import uuid
import time
from dotenv import load_dotenv
import os
import random
import json
import urllib.parse

# LOCAL IMPORTS
from .universal_function import *

load_dotenv()

dmart_cities = [
    "Abohar",
    "Abu Road",
    "Achampet",
    "Achrol",
    "Adampur",
    "Addanki",
    "Addateegala",
    "Adilabad",
    "Adimali",
    "Adoni",
    "Adoor",
    "Afzalpur",
    "Agali",
    "AGARTALA",
    "Agra",
    "Ahmedabad-Gandhinagar",
    "Aizawl",
    "Ajeetgarh",
    "Ajmer",
    "Ajnala",
    "Akaloor",
    "Akbarpur",
    "Akbarpur-UP",
    "Aklera",
    "Akola",
    "Alair",
    "Alakode",
    "Aland",
    "Alappuzha",
    "Aliganj",
    "Aligarh",
    "Aligarh District",
    "ALIPURDUAR",
    "Alirajpur",
    "Allagadda",
    "Allahabad",
    "Alleppey",
    "Almora",
    "ALNAVAR",
    "Alote",
    "Alur",
    "Aluva",
    "Alwar",
    "Amalapuram",
    "Amangal",
    "Amanganj",
    "Amarapuram",
    "Amaravathi",
    "Amarpatan",
    "Amarwara",
    "Ambala",
    "Ambasamudram",
    "Ambuj Nagar",
    "Ambur",
    "Amethi District",
    "Amiliya",
    "Amla",
    "Amravati",
    "Amreli",
    "Amritsar",
    "Amroha District",
    "Anand",
    "Anandnagar",
    "Anandpur Sahib",
    "Anantapur District",
    "Anantnag",
    "Andaman and Nicobar",
    "Angul",
    "Anjumoorthy",
    "Ankleshwar",
    "Ankola",
    "Annur",
    "Anpara",
    "Anthiyour",
    "Anuppur",
    "Anupshahar",
    "Aonla",
    "Arakkonam",
    "Araku",
    "Arambag",
    "Arani",
    "Araria",
    "Areacode",
    "Arimbur",
    "Ariyalur",
    "Armoor",
    "ARRAH",
    "Arsikere",
    "Aruppukkottai",
    "ARWAL",
    "Asansol",
    "Ashok Nagar",
    "Ashta",
    "Asifabad",
    "ASIKA",
    "Asind",
    "Assaigoli",
    "ASTARANGA",
    "Aswaraopeta",
    "Atarra",
    "Athagad",
    "Athani",
    "Atmakur",
    "Atmakur-AP",
    "Atmakur-TS",
    "Attingal",
    "Attur",
    "AUL",
    "Aunrihar",
    "Aurad",
    "Auraiya",
    "Aurangabad",
    "Aurangabad(BH)",
    "Avanigadda",
    "Avinashi",
    "Ayodhya District",
    "Ayoor",
    "Azamgarh",
    "Azhagappapuram",
    "B Kothakota",
    "Babasagar",
    "Baberu",
    "Babrala",
    "BABUJANG",
    "BACHHRAWAN",
    "BADAGADA",
    "BADAMBA",
    "Badami",
    "Baddi",
    "Badlapur",
    "Badnagar",
    "Badnaur",
    "Badvel",
    "Bagalkot",
    "Bagepalli",
    "Bageshwar",
    "Baghpat District",
    "BAGNAN",
    "Bagru",
    "Bagula",
    "Bahadurgarh",
    "Bahal",
    "Baheri",
    "BAHRAICH",
    "BAIHATA",
    "Baijnath-UK",
    "Bailhongal",
    "Bajag",
    "Bajore",
    "Bakewar",
    "Bakhtiarpur",
    "Balaghat",
    "Balangir",
    "Balaran",
    "Balasore",
    "Balesar",
    "Baleswar",
    "Ballia",
    "BALLIGUDA",
    "Balotra",
    "BALRAMPUR",
    "Balussery",
    "BAMRA",
    "Banda",
    "Bandikui",
    "Bangalore",
    "Bangalore Rural",
    "Bangana",
    "Bangaon",
    "Bangarmau",
    "Bangarpet",
    "Banka",
    "Bankapura",
    "Bankura",
    "Bansi",
    "Banswada",
    "Banswara",
    "Bantwal",
    "Bapatla",
    "Barabanki District",
    "Barakar",
    "Baran",
    "Baraut",
    "Bardhaman",
    "Bardoli",
    "Bareilly",
    "Bareja",
    "Bareli",
    "Bargarh",
    "Barh",
    "Barhaj",
    "Barhalganj",
    "Barhi",
    "Bari Sadri",
    "Baripada",
    "Bariya",
    "Barmer",
    "Barnala",
    "Barodia",
    "BARPETA",
    "Barwani",
    "Basavakalyan",
    "Basavana Bagewadi",
    "Basirhat",
    "Bassi",
    "BassiRJ",
    "Bastar",
    "Basti",
    "Batala",
    "Bathinda",
    "Bavla",
    "Bayana",
    "Beawar",
    "Begowal",
    "Begumganj",
    "Begusarai",
    "BEHRAMPUR",
    "Bejjanki",
    "Belgaum",
    "Bellampalli",
    "Bellary",
    "Belthangady",
    "Belur",
    "BENIPATTI",
    "BENIPUR",
    "Beohari",
    "Berachampa",
    "Berasia",
    "Berhampur",
    "Berinag",
    "Betamcherla",
    "Bethamangala",
    "Bettiah",
    "Betul",
    "Bhadaur",
    "Bhaderwah",
    "Bhadohi",
    "Bhadrachalam",
    "Bhadradri Kothagudem District",
    "Bhadrak",
    "Bhadrak District",
    "BHAGALPUR",
    "Bhagpat",
    "Bhainsa",
    "Bhalki",
    "Bhandara",
    "Bhangar",
    "BHANJANAGAR",
    "Bhanpura",
    "Bharuch",
    "BHARWARA",
    "Bhatewar",
    "Bhathat",
    "Bhatkal",
    "Bhavnagar",
    "Bhawani Mandi",
    "Bheemunipatnam",
    "Bhilwara",
    "Bhimadole",
    "Bhimavaram",
    "Bhimtal",
    "Bhind",
    "Bhinga",
    "Bhinmal",
    "Bhiwadi",
    "Bhiwani",
    "Bhogapuram",
    "Bhojpur",
    "Bhongir",
    "Bhopal",
    "Bhopal Rural",
    "BHORE",
    "BHUBAN",
    "Bhubaneshwar-Cuttack",
    "Bhubaneswar Rural",
    "Bhupalpally",
    "Bhuvanagiri",
    "Bichhiya",
    "Bidar District",
    "Bidhuna",
    "Bihar Sharif",
    "Bihta",
    "Bijainagar",
    "Bijapur",
    "BIJNOR",
    "Bijpur",
    "Bikaner",
    "Bikkavolu",
    "Bilara",
    "Bilaspur(CGH)",
    "Bilaspur-HP",
    "Bilaspur-HR",
    "Bilaspur-UP",
    "Bilimora",
    "Billawar",
    "Bina",
    "Binaganj",
    "Birbhum",
    "BIRPARA",
    "Bisalpur",
    "Bishnupur",
    "Boath Buzurg",
    "Bobbili",
    "Bodhan",
    "BOKAKHAT",
    "Bokaro",
    "Bolpur",
    "Bonakal",
    "BONGAIGAON",
    "BONGAON",
    "Bonli",
    "Borsad",
    "Botad",
    "Boudh",
    "BRAHMAPUR",
    "BRAJRAJNAGAR",
    "Brijmanganj",
    "Budaun",
    "Buhana",
    "Bulandshahr",
    "Bulandshahr District",
    "Bundi",
    "Burhanpur",
    "Butibori",
    "Buxar",
    "Byadagi",
    "Byadgi",
    "Byndoor",
    "Cachar",
    "Canning",
    "Chagalamarri",
    "ChakiaUP",
    "Chaklasi",
    "Chaksu",
    "Chalakudy",
    "Challakere",
    "Chamarajanagar",
    "Chameli",
    "Chamoli",
    "Champhai",
    "CHANDANKIYARI",
    "Chandauli",
    "Chandausi",
    "CHANDBALI",
    "Chanderi",
    "Chandigarh Tricity",
    "CHANDIKHOL",
    "Chandpur",
    "Chandrapur",
    "Chandur Bazar",
    "Changanacherry",
    "Changlang",
    "Channagiri",
    "Channapatna",
    "Channarayapatna",
    "Channarayapattana",
    "Charkhi Dadri",
    "Chatra",
    "Chaumahla",
    "Chavassery",
    "Chengannur",
    "Chennai",
    "Chennai Rural",
    "Cherial",
    "CHERLA",
    "Cherpulassery",
    "Chetpet",
    "Cheyyar",
    "CHHAPRA",
    "Chhatarpur",
    "CHHENDIPADA",
    "Chhibramau",
    "Chhindwara",
    "Chhoti Sadri",
    "Chhutmalpur",
    "CHIKITI",
    "Chikkaballapura District",
    "Chikkamagalur",
    "Chikkanayakanahalli",
    "Chikodi",
    "Chilakaluripet",
    "Chimakurthy",
    "Chincholi",
    "Chingavanam",
    "Chinhat",
    "Chinnasalem",
    "Chinnur",
    "Chintalpudi",
    "Chintamani",
    "Chintapalli",
    "Chintoor",
    "Chintpurni",
    "Chirala",
    "Chiramanangad",
    "Chirgaon",
    "Chitradurga",
    "Chitrakoot",
    "Chittapur",
    "Chittaranjan",
    "Chittaurgarh",
    "Chittoor District",
    "Chittor District",
    "Chodavaram",
    "Cholapur",
    "Chomu",
    "Chopan",
    "Choppadandi",
    "Chotila",
    "Choutuppal",
    "chungatra",
    "Chunnar",
    "Churu",
    "Cochin",
    "Coimbatore",
    "Coimbatore Rural",
    "Colonejganj",
    "COOCHBEHAR",
    "Coonoor",
    "Cuddalore",
    "Cuddapah",
    "Cumbum",
    "CumbumAP",
    "Cuttack",
    "Dabaspete",
    "Dabra",
    "Dadri",
    "Dahegam",
    "Dahegaon",
    "Dalhousie",
    "Daman",
    "Damoh",
    "Dandeli",
    "Dantewada",
    "Danthalapally",
    "Darbhanga",
    "Dariyabad",
    "Darjiling",
    "Darrang",
    "Daryapur Banosa",
    "DASPALLA",
    "Dasuya",
    "Dataganj",
    "Dausa",
    "Davangere",
    "Debagarh",
    "Deesa",
    "Degana",
    "DehraDun",
    "Delhi",
    "Denkanikottai",
    "DeogarhRJ",
    "Deoghar",
    "Deoli-RJ",
    "Deoria",
    "Deosar",
    "Deotalab",
    "Dera Bassi",
    "Devadurga",
    "Devarakonda",
    "Dewas",
    "DHAKA",
    "DHAKUAKHANA",
    "Dhalai",
    "Dhamnod",
    "Dhampur",
    "Dhamtari",
    "Dhanbad",
    "Dhandhuka",
    "Dhanghata",
    "Dhar",
    "Dharamkot",
    "Dharampur",
    "Dharapuram",
    "Dharchula",
    "Dhariyawad",
    "Dharmapuri-TS",
    "Dharwad",
    "Dhaurahara",
    "Dhemaji",
    "Dhenkanal",
    "DHOLI",
    "Dholka",
    "Dholpur",
    "Dhone",
    "Dhubri",
    "Dhuri",
    "Dibai",
    "DIBRUGARH",
    "Didihat",
    "Didwana",
    "DIGAPAHANDI",
    "DIGBOI",
    "Dildar Nagar",
    "Dimapur",
    "Dinanagar",
    "DINARA",
    "Dindigul",
    "DINHATA",
    "Diu",
    "Doddaballapura",
    "Doiwala",
    "Domariyaganj",
    "DOOMDOOMA",
    "Doranala",
    "Dostpur",
    "Draksharamam",
    "Dudhinagar",
    "Dudu",
    "Dulchehra",
    "DULIAJAN",
    "Dullahpur",
    "Dumka",
    "Dumraon",
    "Dungarpur",
    "Durg",
    "Dwarahat",
    "Dwaraka Tirumala",
    "East Champaran",
    "East Garo Hills",
    "East Godavari District",
    "East Kameng",
    "East Khasi Hills",
    "East Midnapore",
    "East Siang",
    "East Sikkim",
    "East Singhbhum",
    "East-Godavari-2",
    "Edappal",
    "Edavanna",
    "Eedu",
    "EKMA",
    "Eluru",
    "Eral",
    "Erode",
    "Etah",
    "Etawah",
    "Ezhupunna",
    "Faizabad",
    "Falna",
    "Faridabad",
    "Faridkot",
    "Faridpur",
    "Farrukhabad",
    "Fatehabad",
    "Fatehgarh",
    "Fatehgarh Sahib District",
    "Fatehnagar",
    "Fatehpur",
    "Fatehpur-RJ",
    "Fazilka",
    "Firozabad",
    "Firozpur",
    "Gadag",
    "Gadarwara",
    "Gadwal",
    "Gahmar",
    "Gairsain",
    "Gajapati",
    "Gajapatinagaram",
    "Gajraula",
    "Galiveedu",
    "GALLERI",
    "Ganga Nagar",
    "Gangapur City",
    "Gangapur-RJ",
    "Gangavathi",
    "Ganj Basoda",
    "Ganjam",
    "Ganjam",
    "Ganjdundwara",
    "Gannavaram",
    "Garhshanker",
    "Garhwa",
    "Gariaband",
    "Garividi",
    "GARJANPUR",
    "Garkha",
    "Garoth",
    "Gauribidanur",
    "Gautam Buddha Nagar District",
    "Gaya",
    "Ghanpur",
    "Ghansali",
    "Gharsana",
    "Ghatampur",
    "Ghati Billan",
    "Ghator",
    "Ghaziabad",
    "Ghazipur",
    "Ghosi",
    "Ghughus",
    "Ghugri",
    "Ghumarwin",
    "Giddarbaha",
    "Giridh",
    "Goa",
    "Goalpara",
    "Gobichettipalayam",
    "Godda",
    "Godhra",
    "GOGAMUKH",
    "Gogunda",
    "Gohana",
    "Gokak",
    "Gokavaram",
    "GOLAGHAT",
    "Gonda District",
    "Gondia",
    "Gonikoppal",
    "Gooty",
    "GOPALAPUR",
    "Gopalganj",
    "GOPALNAGAR",
    "Gopiganj",
    "Gorakhpur",
    "Gorantla",
    "Gotan",
    "Gudalur",
    "Gudivada",
    "Gudiyatham",
    "Gudiyattam",
    "Gudur",
    "Gudur-TS",
    "Gulbaraga",
    "Gulbarga",
    "GUMIA",
    "Gumkhal",
    "Gumla",
    "Gummudipoondi",
    "Guna",
    "Gundlupet",
    "Guntakal",
    "Guntur",
    "Guntur-Rural",
    "Gurdaspur",
    "Gurgaon",
    "Gurmatkal",
    "Gursahaiganj",
    "Gurugram Rural",
    "Guruvayoor",
    "Guskhara",
    "Guwahati",
    "Guwahati Rural",
    "Gwalior",
    "Habra",
    "Hagaribommanahalli",
    "Haidargarh",
    "Hailakandi",
    "Hajipur",
    "Haldia",
    "Haldwani",
    "Halflong",
    "Haliyal",
    "Hamirpur",
    "Hamirpur-UP",
    "Hanamkonda",
    "Hangal",
    "Hansi",
    "Hanskhali",
    "Hanumangarh",
    "Hanur",
    "Hapur",
    "Harda",
    "Hardoi",
    "Haridwar",
    "Harihara",
    "Haripad",
    "Haripal",
    "Haripurdhar",
    "Harpanahalli",
    "Harur",
    "Haryana",
    "HARYANA_3PL",
    "Hasanpur",
    "Hasnabad",
    "Hassan",
    "Hathras",
    "Hatta",
    "Haveri",
    "Hayathnagar",
    "Hazaribag",
    "HELENCHA",
    "Herbertpur",
    "HILSA",
    "Himachal Pradesh",
    "HIMACHAL PRADESH_3PL",
    "Himatnagar",
    "Hindaun",
    "Hindupur",
    "HINGALGANJ",
    "HINJILICUT",
    "Hiranagar",
    "Hirekerur",
    "Hiriyur",
    "Hisar",
    "Holenarasipur",
    "Honnali",
    "Honnavar",
    "Hooghly",
    "Hooghly District",
    "Hoovina Hadagali",
    "Hosadurga",
    "Hosanagar",
    "Hoshangabad",
    "Hoshiarpur",
    "Hospet",
    "Hosur",
    "Howrah",
    "Hubli",
    "Huliyar",
    "Humnabad",
    "Hunsur",
    "Husnabad",
    "Huzur Nagar",
    "Huzurabad",
    "Hyderabad",
    "Hyderabad Rural",
    "Ichchapuram",
    "Ichoda",
    "Iddukki",
    "Ikauna",
    "ILIPUR",
    "Ilkal",
    "IMAMGANJ",
    "Imphal West",
    "Indi",
    "Indore",
    "Indore Rural",
    "Irinjalakuda",
    "Itarsi",
    "Itava",
    "Itawa",
    "Itia Thok",
    "Jabalpur",
    "Jadcherla",
    "Jagaluru",
    "JAGANNATHPRASAD",
    "Jagatsinghapur",
    "Jagatsinghpur",
    "JAGDISHPUR",
    "Jagraon",
    "Jagtial",
    "Jahangirabad",
    "Jahu",
    "JAIGAON",
    "Jainoor",
    "Jaintia Hills",
    "Jaipur",
    "Jaipur Rural",
    "Jaisalmer",
    "Jaisinghnagar",
    "Jaitwara",
    "Jajapur",
    "Jajpur",
    "Jakh",
    "Jalalabad",
    "Jalalpur",
    "Jalalpur-UP",
    "Jalandhar",
    "Jalaun",
    "Jalesar",
    "Jalore",
    "JALPAIGURI",
    "Jamkhandi",
    "Jammikunta",
    "JAMMU & KASHMIR_3PL",
    "Jammu Kashmir",
    "Jamshedpur",
    "Jamtara",
    "Jamui",
    "Jamuria",
    "Jangaon",
    "Jangareddygudem",
    "Janjgir-champa",
    "Jannaram",
    "Jaora",
    "Jashpur",
    "Jatara",
    "Jaunpur",
    "Jawad",
    "Jayankondam",
    "Jehanabad",
    "Jewar",
    "Jewargi",
    "Jhabua",
    "Jhadol",
    "Jhajjar",
    "Jhalawar",
    "JHANJHARPUR",
    "Jhansi",
    "Jharsuguda",
    "Jhunjhunu",
    "Jhunku",
    "Jiyanpur",
    "Jodhpur",
    "Joginder Nagar",
    "Jogipet",
    "JORHAT",
    "Joshimath",
    "Jubbal",
    "Jukhala",
    "Junnardeo",
    "Kadaba",
    "Kadapa",
    "Kadi",
    "Kadiri",
    "KADOBAHAL",
    "Kadpadi",
    "Kadur",
    "Kaghaznagar",
    "Kaikaluru",
    "Kaimur (Bhabua)",
    "Kaithal",
    "Kakinada",
    "Kalaburagi",
    "Kalahandi",
    "Kalasa",
    "Kalghatgi",
    "Kalinga Nagar",
    "Kallakurichi",
    "Kallikkad",
    "Kalluru",
    "Kalmeshwar",
    "Kalna",
    "Kalol",
    "KalolHP",
    "Kalpetta",
    "Kalwakurthy",
    "Kalyandurg",
    "KALYANI",
    "KAMAKHYANAGAR",
    "Kamareddy District",
    "Kambadur",
    "Kamptee",
    "Kamrup",
    "Kanakapura",
    "Kanchipuram",
    "Kandhamal",
    "Kandukur",
    "Kangan",
    "Kangeyam",
    "Kangra",
    "Kanigiri",
    "Kanjarakatte",
    "Kanjiramattom",
    "Kanker",
    "Kannapuram",
    "Kannauj",
    "Kannur",
    "Kanpur",
    "Kanthi",
    "Kapadvanj",
    "Kapasan",
    "Kaptanganj",
    "Kapurthala",
    "Karaikal",
    "Karaikudi",
    "Karauli",
    "Karbi Anglong",
    "Karera-MP",
    "Karim Nagar",
    "Karimba",
    "Karimganj",
    "Karimnagar",
    "Karkala",
    "Karnal",
    "Karsog",
    "Karukachal",
    "Karur",
    "Karwar",
    "Kasaragod",
    "Kasganj",
    "Kashipur",
    "Katangi",
    "Kathipudi",
    "Kathua",
    "Katihar",
    "Katni",
    "Katol",
    "Kattappana",
    "Katwa",
    "Kauriram",
    "Kavali",
    "Kawardha",
    "Kayamkulam",
    "Kazipet",
    "Kekri",
    "Kelwara",
    "Kendrapara",
    "Kendujhar",
    "Kerakat",
    "Kerur",
    "Kesali",
    "Keshoraipatan",
    "Keylong",
    "Khadda",
    "Khagaria",
    "Khairabad",
    "Khajuraho",
    "KHALARI-JR",
    "Khalilabad",
    "Khambhat",
    "Khammam",
    "Khanapur",
    "Khanapur-TS",
    "Khandela",
    "Khandwa",
    "Khanna",
    "Khanpur",
    "Kharagpur",
    "Khargone",
    "Khatauli",
    "Khategaon",
    "Khatima",
    "Khatu Khurd",
    "Kheda",
    "Kheragarh",
    "Khergam",
    "Kheri",
    "Kherwara",
    "Khimsar",
    "Khinwara",
    "KHIZASARAI",
    "KHODAGANJ",
    "Khorda",
    "Khordha",
    "KHUNTI",
    "Khurai",
    "Khutar",
    "Kilimanoor",
    "Kinnaur",
    "Kiphire",
    "Kishanganj",
    "Kishangarh",
    "Kishni",
    "Kittur",
    "Kochi",
    "Kochi Rural",
    "Kodad",
    "Kodaikanal",
    "KODALA",
    "Koderma",
    "Kodumudi",
    "Kodungallur",
    "Koduru",
    "Kokrajhar",
    "kolar",
    "Kolasib",
    "Kolayat",
    "Kolhapur",
    "Kolhar",
    "Kolkata",
    "Kolkata Rural",
    "Kollam",
    "Kollapur",
    "Kollegala",
    "KONARK",
    "Konaseema District",
    "Konch",
    "Kondapi",
    "Koothattukulam",
    "Koppal",
    "Koraput",
    "Koratagere",
    "Koratla",
    "Korba",
    "Koriya",
    "Koruprolu",
    "Kosgi",
    "Kota",
    "Kotagiri",
    "Kotdwara",
    "Kothagudem",
    "Kothapalli",
    "Kotkapura",
    "Kotma",
    "Kotputli",
    "Kottarakkara",
    "Kottayam",
    "Kotturu",
    "Kotturu-AP",
    "Kovilpatti",
    "Kovvur",
    "Kowthal",
    "Koyilandy",
    "Koyyuru",
    "Kozhenchery",
    "Kozhikode",
    "Krishna District",
    "Krishnagiri",
    "Krishnarajanagara",
    "Krishnarajngr",
    "Krishnarajpet",
    "KUCHAIKOTE",
    "Kuchaman City",
    "KUCHINDA",
    "Kudair",
    "Kudligi",
    "Kukanoor",
    "Kukshi",
    "Kumarganj",
    "Kumbakonam",
    "Kumily",
    "Kumta",
    "Kundapura",
    "Kundli",
    "Kunigal",
    "Kuppam",
    "Kurnool",
    "Kurugodu",
    "Kurukshetra",
    "Kurupam",
    "Kushalnagar",
    "Kushinagar",
    "Kushtagi",
    "Kusumanchi",
    "Kuthumkal",
    "Kuthuparamba",
    "Kuttiady",
    "Kuttikol",
    "Ladakh",
    "Ladwa",
    "Lahar",
    "Lakheri",
    "Lakhimpur",
    "Lakhisarai",
    "Lakhnadon",
    "Laksar",
    "Lal Gopalganj",
    "Lalitpur",
    "Lalsot",
    "Lambhua",
    "Latehar",
    "Lavkush Nagar",
    "Lawngtlai",
    "Laxmangarh",
    "Laxmangarh-RJ",
    "Linga",
    "Lingasugur",
    "Lohaghat",
    "Lohardaga",
    "Lohit",
    "Longleng",
    "Lower Dibang Valley",
    "Lower Subansiri",
    "Lucknow",
    "Lucknow Rural",
    "Lucknow-Kanpur",
    "Ludhiana",
    "Ludhiana District",
    "Lunawada",
    "Lunglei",
    "Lunkaransar",
    "Luxettipet",
    "Macherla",
    "Machhiwara",
    "Machilipatnam",
    "Madakasira",
    "Madanapalle",
    "Madanapalli",
    "Madanpur",
    "Maddur",
    "Madgulapally",
    "Madhepura",
    "Madhoganj",
    "Madhubani",
    "Madhugiri",
    "MADHYA PRADESH_3PL",
    "Madikeri",
    "Madurai",
    "Madwas",
    "Magadi",
    "Mahabubabad",
    "Mahabubnagar",
    "Mahadevpur",
    "Mahalingpur",
    "Maharajapuram",
    "MAHARAJGANJ-BH",
    "Mahasamund",
    "Mahe",
    "Mahendragarh-HR",
    "Maheshwar",
    "Mahoba",
    "Maholi",
    "Mahrauni",
    "Mahwa",
    "Maihar",
    "Mainpuri",
    "MAIRWA",
    "Majhgawa",
    "MAKHDUMPUR",
    "Makrana",
    "Maksudangarh",
    "Makthal",
    "Malanjkhand",
    "Malappuram",
    "Malavalli",
    "MALDA",
    "Malerkotla",
    "Malhera",
    "Malihabad",
    "Malkangiri",
    "Mallapur",
    "Malmaliya",
    "Malout",
    "Malpura",
    "Malsisar",
    "Malur",
    "Mammit",
    "Manali",
    "Manamelkudi",
    "Mananthavadi",
    "Manasa",
    "Manawar",
    "Mancherial",
    "Manda",
    "Mandalgarh",
    "Mandapeta",
    "Mandi Dabwali",
    "Mandideep",
    "Mandla",
    "Mandphiya",
    "Mandsaur",
    "Mandya",
    "MANGALDOI",
    "Mangalore",
    "Manipal",
    "Manjeshwar",
    "Manopad",
    "Mansa",
    "Manthani",
    "Manuguru",
    "Manvi",
    "MARHOWARAH",
    "Mariahu",
    "Marigaon",
    "Markapur",
    "Marthandam",
    "Martur",
    "Marwar Junction",
    "MASAURHI",
    "Masrakh",
    "Mathania",
    "Mathura",
    "Mau",
    "Mauranipur",
    "Mayiladuthurai",
    "Mayurbhanj",
    "Mecheda",
    "Medak District",
    "Medinipur",
    "Meerut",
    "Meerut District",
    "Meham",
    "Mehmedabad",
    "Mehsana",
    "Melur",
    "Memari",
    "Menhdawal",
    "Merta",
    "Metpally",
    "Mettala",
    "Mettupalayam",
    "Mettur",
    "Mhow",
    "Milak",
    "MINAKHAN",
    "MIRGANJ",
    "Miryalaguda",
    "Mirzapur",
    "Miyanganj",
    "Modasa",
    "Modinagar District",
    "Moga",
    "Mogullapally",
    "Mohali",
    "Mohammadabad",
    "Mohammadi",
    "MOHAMMADPUR",
    "MOHANA",
    "Mohopada",
    "Mokama",
    "Mokokchung",
    "Molakalmuru",
    "Mominpet",
    "Moodabidri",
    "Moradabad",
    "Morena",
    "Morshi",
    "Motebeennura",
    "Mothkur",
    "Motihari",
    "Mudarangady",
    "Muddebihal",
    "Mudhol",
    "Mudigere",
    "Mudigubba",
    "Mughal Sarai",
    "Muktsar",
    "Mulbagal",
    "Multai",
    "Mulugu",
    "Mumbai",
    "Mumbai Rural",
    "Mundakayam",
    "Mundgod",
    "Mungaoli",
    "Munger",
    "Mungra Badshahpur",
    "Munnar",
    "Munuvalli",
    "Muradnagar",
    "Murshidabad",
    "Muskara",
    "Mussoorie",
    "Muthukulathur",
    "Muvattupuzha",
    "Muzaffarnagar District",
    "Muzaffarpur",
    "Muzzafarpur",
    "Mysore",
    "Mysore Rural",
    "Nabadwip",
    "Nabarangapur",
    "Nabha",
    "Nadaun",
    "Nadia",
    "Nadiad",
    "Nadoti",
    "Nagamangala",
    "Nagaon",
    "Nagapattinam",
    "Nagari",
    "Nagarkurnool",
    "Nagaur",
    "Nagda",
    "Nagercoil",
    "Nagina",
    "Nagod",
    "Nagpur",
    "Nagpur Rural",
    "Nahan",
    "Naharlagun",
    "Naidupeta",
    "Naina Devi",
    "Naini",
    "Nainital",
    "Nainwa",
    "Najibabad",
    "NAKASHIPARA",
    "Nakerakal",
    "Nakodar",
    "Nalanda",
    "Nalbari",
    "Nalgonda",
    "Nallajerla",
    "Namakkal",
    "Nandikotkur",
    "Nandyal",
    "Nanjangud",
    "Nanpara",
    "Narasannapeta",
    "Narasaraopet",
    "NARASINGHPUR",
    "Narayankhed",
    "Narayanpet",
    "NARAYANPUR",
    "Narikkuni",
    "Narketpalle",
    "Narmetta",
    "Narnaul",
    "Narsampet",
    "Narsapur",
    "Narsapur-TS",
    "Narsinghgarh",
    "Narsinghpur",
    "Narsipatnam",
    "Nashik",
    "Nasirabad",
    "Naugarh",
    "Nautanwa",
    "Navalgund",
    "Navipet",
    "Navsari",
    "Nawabganj",
    "Nawabganj-UP",
    "Nawada",
    "Nawalgarh",
    "Nawanshahr",
    "Nayagarh",
    "NAZIRA",
    "NAZIRPUR",
    "Nedumangad",
    "Nedumkandam",
    "Neem ka Thana",
    "Neemuch",
    "Nellore",
    "Nenmara",
    "Nepanagar",
    "Nereducharla",
    "Neyyattinkara",
    "Nichlaul",
    "Nighasan",
    "Nileshwar",
    "NIMAPARA",
    "Nimbahera",
    "Nipani",
    "Nirmal",
    "Nizamabad District",
    "Nizamabad-UP",
    "Nohar",
    "Noida Rural",
    "Noida-Ghaziabad",
    "Nokha",
    "North 24 Parganas",
    "North Cachar Hills",
    "North Dinajpur",
    "NORTH LAKHIMPUR",
    "North Paravur",
    "North Sikkim",
    "North Tripura",
    "Nuapada",
    "NULL",
    "Nuzvid",
    "Oddanchatram",
    "Ongole",
    "Ooty",
    "Orai",
    "Ottapidaram",
    "Pachore",
    "PadampurRJ",
    "Paderu",
    "Padmajiwadi",
    "Padrauna",
    "Paithani",
    "Pakala",
    "PAKRIBARWAN",
    "Pakur",
    "Pakyong",
    "Palacode",
    "Palakkad",
    "Palakollu",
    "Palakonda",
    "Palamaner",
    "Palamau",
    "Palani",
    "Palanpur",
    "Palasa",
    "Pali Birsinghpur",
    "Palitana",
    "Palladam",
    "Palwal",
    "Pamarru",
    "Pamuru",
    "Panchkula",
    "Pandhurna",
    "Pandikkad",
    "Pandua",
    "Pangodu",
    "Panipat",
    "Panja",
    "Panna",
    "Pansemal",
    "Panvel",
    "Paonta Sahib",
    "Paota",
    "Papum Pare",
    "Paramakudi",
    "Parappa",
    "Parasia",
    "Pardi",
    "Parippally",
    "Parkal",
    "Parvathipuram",
    "Parwanoo",
    "Paschim Bardhaman",
    "Patan",
    "Patancheru",
    "Pathanamthitta",
    "Pathankot",
    "Pathapatnam",
    "Patiala",
    "Patna",
    "Patna Rural",
    "Patran",
    "Patti",
    "Patti-UP",
    "Pattukkottai",
    "Pauri",
    "Pavagada",
    "PAVAPURI",
    "Pawai",
    "Pazhayannur",
    "Pedabayalu",
    "Pedapadu",
    "PEDDAPALLI",
    "Pehowa",
    "Pench",
    "Pendra",
    "Pennadam",
    "Pennagaram",
    "Penugonda",
    "Peralam",
    "Perambalur",
    "Perambra",
    "Perinthalmanna",
    "Perumbavoor",
    "Perunali",
    "Perundurai",
    "PETERBAR",
    "Petlad",
    "Petlawad",
    "Phagwara",
    "Phalodi",
    "Phalsund",
    "Phek",
    "Phephna",
    "Phulera",
    "PHUSRO",
    "Pichhore",
    "Piduguralla",
    "Pihani",
    "Pilakhua District",
    "Pilani",
    "Pileru",
    "Pilibanga",
    "Pilibhit",
    "Pilkhuwa",
    "Pindwara",
    "Piparcity",
    "Pipariya",
    "PIPILI",
    "Piriyapatna",
    "PIRO",
    "Pithampur",
    "Pithoragarh",
    "PLASSEY",
    "Podili",
    "Poinachi",
    "Pokhran",
    "Polay Kalan",
    "Pollachi",
    "Polur",
    "Ponnamaravathi",
    "Pooh",
    "Poonch",
    "Poonchh",
    "Prakasam",
    "Prakasam District",
    "Pratapgarh District",
    "Pratapgarh-RJ",
    "Pregnapur",
    "Prithvipur",
    "Proddatur",
    "Puducherry",
    "Pudukkottai",
    "Pukhrayan",
    "Pulivendula",
    "Pulpally",
    "Pune",
    "Pune Rural",
    "Punganur",
    "Punjab",
    "PUNJAB_3PL",
    "Puranpur",
    "Purba Bardhaman",
    "Puri",
    "Puruliya",
    "Pushpavanam",
    "Puthukkad",
    "Puttaparthi",
    "Puttur",
    "Puttur-AP",
    "Raebareli District",
    "RAGHUNATHPUR-BR",
    "Rahatgarh",
    "Raibag",
    "Raichur",
    "Raigarh",
    "Raikot",
    "Raila",
    "Raipur",
    "Raipur Karchulion",
    "Raipur-RJ",
    "Raipura",
    "RAIRAKHOL",
    "Raisen",
    "Raisinghnagar",
    "Rajahmundry",
    "Rajamahendravaram",
    "Rajampet",
    "Rajapalayam",
    "RAJASTHAN_3PL",
    "Rajesultanpur",
    "RAJGANJ",
    "Rajgarh",
    "Rajgarh-HP",
    "Rajgarh-MP",
    "RAJGIR",
    "Rajkot",
    "Rajnandgaon",
    "Rajpipla",
    "Rajsamand",
    "Ramagundam",
    "Ramanagara",
    "Ramanathapura",
    "Ramanathapuram",
    "Ramannapeta",
    "Ramdurg",
    "Rameswaram",
    "Ramganj Mandi",
    "Ramgarh",
    "Ramgarh-RJ",
    "Ramnagar",
    "Rampachodavaram",
    "Rampur",
    "Rampur Naikin",
    "Rampura Phul",
    "Ramtek",
    "Ranchha",
    "Ranchi",
    "Ranebennur",
    "RANGPO",
    "Ranihati",
    "Ranikhet",
    "Ranipet",
    "Raniwara",
    "Ranni",
    "Ras",
    "Rasipuram",
    "Rasulabad",
    "Ratangarh",
    "Ratangarh-MP",
    "Ratanpura",
    "Rath",
    "Ratia",
    "Ratlam",
    "Rawatbhata",
    "Rawatsar",
    "Rayachoti",
    "Rayadurgam",
    "Rayagada",
    "Rayaparthi",
    "Razole",
    "Reckong Peo",
    "Reengus",
    "Rehli",
    "Renigunta",
    "Renukoot",
    "Renwal",
    "Reodar",
    "Repalle",
    "Rewa",
    "Rewari",
    "Ri Bhoi",
    "Rishikesh",
    "Robertsganj",
    "Robertsonpet",
    "Rohtak",
    "Rohtas",
    "Rona",
    "Roorkee",
    "Rourkela",
    "RS Pura",
    "Rudauli",
    "Rudhauli",
    "Rudrangi",
    "Rudraprayag",
    "Rudrapur",
    "RUNNISAIDPUR",
    "Rupnagar",
    "S Kota",
    "Sabalgarh",
    "Sagar",
    "Sagara",
    "Sagwara",
    "Saharanpur District",
    "Saharsa",
    "Sahaswan",
    "Sahibganj",
    "Saidabad",
    "Saiha",
    "Sakleshpur",
    "Salcete",
    "Salem",
    "Salempur",
    "SALIPUR",
    "Salumbar",
    "Salur",
    "Samarlakota",
    "Samastipur",
    "Sambalpur",
    "Sambhal District",
    "Sanawad",
    "Sanchore",
    "Sandur",
    "Sangareddy",
    "Sangareddy District",
    "Sangaria",
    "Sangrur",
    "Sankaramangalam",
    "Sankarankovil",
    "Sankarapuram",
    "Sankari",
    "Santipur",
    "Saoner",
    "Sarada",
    "SARAIYA",
    "Saran",
    "Sardarshahr",
    "Sarni",
    "Sasaram",
    "Sathupally",
    "Sathyamangalam",
    "Satna",
    "Sattur",
    "Saundatti",
    "Sausar",
    "Savadatti",
    "Sawai Madhopur",
    "Sedam",
    "Seetharampram",
    "Sehore",
    "Semariya",
    "Sendhwa",
    "Seoni",
    "Seraikela-kharsawan",
    "Serchhip",
    "Sewarhi",
    "Shadnagar",
    "Shahabad Markanda",
    "Shahabad-UP",
    "Shahapur",
    "Shahdol",
    "Shaheed Bhagat Singh Nagar",
    "Shahganj",
    "Shahgarh",
    "Shahjahanpur",
    "Shahpura",
    "ShahpuraMP",
    "Shajapur",
    "Shambhu",
    "Shamli",
    "Shanivarasanthe",
    "Sheikhpura",
    "SHEOHAR",
    "SHEONAR",
    "Sheopur",
    "Shiggaon",
    "Shikaripur",
    "Shikohabad",
    "SHILLONG",
    "Shilong",
    "Shimla",
    "Shimoga",
    "Shiralakoppa",
    "Shivpuri",
    "Sholinghur",
    "Shoranur",
    "Shorapur",
    "SHRAVASTI",
    "Shri Dungargarh",
    "Shrimadhopur",
    "Shujalpur",
    "Sibsagar",
    "Siddapur",
    "Siddhpur",
    "Siddipet District",
    "Sidhauli",
    "Sidhi",
    "Sidlaghatta",
    "Sihor",
    "Sihora",
    "Sikandrabad",
    "Sikar",
    "Sikriganj",
    "SILCHAR",
    "Siliguri",
    "Silvassa",
    "Silwani",
    "Simalwara",
    "Simdega",
    "Sindagi",
    "Sindhanur",
    "Sindudurg",
    "Singarayakonda",
    "SINGHIA",
    "Singrauli",
    "Sira",
    "Sirathu",
    "Sircilla District",
    "SIRDALA",
    "Sirikonda",
    "Sirkazhi",
    "Sirohi",
    "Sirsa",
    "Sirsi",
    "Siruguppa",
    "Sirvella",
    "Sitamarhi",
    "Sitapur",
    "Sitarganj",
    "Sivaganga",
    "Sivakasi",
    "SIVASAGAR",
    "Siwan",
    "Siyana",
    "Sleemnabad",
    "Sohagi",
    "Sojat",
    "Someshwar",
    "Sompeta",
    "Sonapur",
    "SONBARSA",
    "Sonepur",
    "Songadh",
    "Sonipat",
    "Sonitpur",
    "Soraba",
    "Soraon",
    "Soro",
    "South 24 Parganas",
    "South 24 Parganas District",
    "South Dinajpur",
    "South Garo Hills",
    "South Sikkim",
    "South Tripura",
    "Sri City",
    "Sri Hargobindpur",
    "Srikakulam Disctrict",
    "Srikalahasti",
    "Srinagar",
    "Srinagar-UK",
    "Sringeri",
    "Srinivaspur",
    "Sriperumbudur",
    "Srirangapatna",
    "Srisailam",
    "Srivijaynagar",
    "Sujangarh",
    "Sullia",
    "Sullurupeta",
    "Sultan Bathery",
    "Sultana",
    "SULTANGANJ",
    "Sultanpur District",
    "Sultanpur Lodhi",
    "Sumerpur",
    "Sunam",
    "Sundar Nagar",
    "Sundergarh",
    "Sundla",
    "Supaul",
    "SURAJGARHA",
    "Surajpur jhikla",
    "Surat",
    "Surat Rural",
    "Suratgarh",
    "Surathkal",
    "Surguja",
    "Suryapet District",
    "SWARUPNAGAR",
    "Tadepalligudem",
    "Tadipatri",
    "Tadoor",
    "Tadvai",
    "Taherpur",
    "Tahliwal",
    "Talbahat",
    "Talikoti",
    "Tamluk",
    "Tanakpur",
    "Tanda",
    "Tandur-TL",
    "Tanuku",
    "Tarakeswar",
    "Tarana",
    "Taranagar",
    "Tarn Taran Sahib",
    "Tarsikka",
    "Tawang",
    "Tehri",
    "Tekkali",
    "Tenali",
    "Tendukheda",
    "Tenkasi",
    "Tezpur",
    "Thachanattukara",
    "Thakurnagar",
    "Thalassery",
    "Thalavadi",
    "Thamarassery",
    "Thanesar",
    "Thanjavur",
    "Tharali",
    "Theni",
    "Theog",
    "Thikri",
    "Thirthahalli",
    "Thirumalagiri",
    "Thiruthuraipoondi",
    "Thiruttani",
    "Thiruvadanai",
    "Thiruvananthapuram",
    "Thiruvarur",
    "Thisayanvilai",
    "Thodupuzha",
    "Thoubal",
    "Thrissur",
    "Thuckalay",
    "Thuraiyur",
    "Tijara",
    "Tikamgarh",
    "Tindivanam",
    "Tinsukia",
    "Tiptur",
    "Tirap",
    "Tirora",
    "Tiruchendur",
    "Tiruchengode",
    "Tiruchi",
    "Tirunelveli",
    "Tirupati",
    "Tirupattur",
    "Tiruppur",
    "Tirur",
    "Tiruvalla",
    "Tiruvallur District",
    "Tiruvannamalai",
    "Tirwanganj",
    "Tiryani",
    "Tonk",
    "Tribeni",
    "Trichy",
    "Tripura",
    "Tuensang",
    "Tumakuru",
    "Tundla",
    "Tungaturthi",
    "Tuni",
    "Turuvukere",
    "Tuticorin",
    "Udaipura",
    "Udaipurwati",
    "Udayagiri",
    "Udgir",
    "Udham-Singh-Nagar",
    "Udhampur",
    "Udumalaipettai",
    "Ugar",
    "Ujjain",
    "Ukhra",
    "Ullal",
    "ULUBERIA",
    "Umaria",
    "Umreth",
    "Una-HP",
    "Unjha",
    "UNNAO",
    "Upper Siang",
    "Upper Subansiri",
    "Uravakonda",
    "Usilampatti",
    "Uthangarai",
    "Utnoor",
    "UTTAR PRADESH_3PL",
    "UTTARAKHAND_3PL",
    "Uttarkashi",
    "Vadakara",
    "Vadipatti",
    "Vadodara",
    "Vadodara Rural",
    "Vaidpura",
    "Vaishali",
    "Valanchery",
    "Vallioor",
    "Valsad",
    "Vandavasi",
    "Vaniyambadi",
    "Vapi",
    "Varanasi",
    "Veenavanka",
    "Velgodu",
    "Vellakovil",
    "Vellore",
    "Velur",
    "Vempalli",
    "Venjaramoodu",
    "Venkatagirikota",
    "Venkatgiri",
    "Vidisha",
    "Vidyanagar",
    "Vijapur",
    "Vijayapura",
    "Vijayawada-Guntur",
    "Vijayraghavgarh",
    "Vikarabad",
    "Vilathikulam",
    "Viluppuram",
    "Vinukonda",
    "Virajpet",
    "Viratnagar",
    "Virudhachalam",
    "Virudhunagar",
    "Visakhapatnam",
    "Visakhapatnam District",
    "Visnagar",
    "Vissannapetaa",
    "Vitla",
    "Vizag Rural",
    "Vizianagaram",
    "Vizianagaram Disctrict",
    "Vuyyuru",
    "Vyara",
    "Wadala",
    "Wanaparthy",
    "Wani",
    "Warangal",
    "Waraseoni",
    "Wardha",
    "Warora",
    "Warud",
    "WAZIRGANJ",
    "Weir",
    "West Champaran",
    "West Garo Hills",
    "West Godavari District",
    "West Kameng",
    "West Khasi Hills",
    "West Midnapore",
    "West Siang",
    "West Sikkim",
    "West Singhbhum",
    "West Tripura",
    "West-Godavari",
    "Wyra",
    "Yadgir",
    "Yamuna Nagar",
    "Yanam District",
    "Yaragatti",
    "Yavatmal",
    "Yelburga",
    "Yellamanchili",
    "Yellandu",
    "Yellapur",
    "Yellare",
    "Yellareddipet",
    "Yellareddy",
    "Yemmiganur",
    "Yerragonda Palem",
    "Yerravaram",
    "Zahirabad",
    "Zira",
    "Zirakpur",
    "Zunhebotto"
]

def update_address_in_session(location_data, cookies, headers, session_id):
    for i in range(3):
        try:
            lat = location_data['results'][0]['geometry']['location']['lat']
            long = location_data['results'][0]['geometry']['location']['lng']
            zipcode = location_data['results'][0]['address_components'][-1]['long_name']
            bigbasket_com = uuid.uuid4()
            jarvis_id = uuid.uuid4()
            
            new_cookies = {
                'ufi': '1',
                'bigbasket.com': str(bigbasket_com),
                '_gcl_au': '1.1.995482043.1741792204',
                'jarvis-id': str(jarvis_id),
                'adb': '0',
                '_fbp': 'fb.1.1741792204246.62251282917562310',
                '_ga_FRRYG5VKHX': 'GS1.1.1741792204.1.0.1741792204.60.0.0',
                '_ga': 'GA1.2.1851803795.1741792204',
                '_gid': 'GA1.2.1660596046.1741792204',
                '_gat_UA-27455376-1': '1',
            }
            cookies.update(new_cookies)
            
            new_headers = {
                'content-type': 'application/json',
                'x-caller': 'UI-KIRK',
                'x-channel': 'BB-WEB',
                'x-csurftoken': cookies.get('csurftoken', ''),
                'x-entry-context': 'bb-b2c',
                'x-entry-context-id': '100',
                'x-requested-with': 'XMLHttpRequest',
                'x-tracker': str(uuid.uuid4()),
                'Cookie': dict_to_cookie_string(cookies)
            }
            headers.update(new_headers)

            json_data = {
                'lat': float(lat),
                'long': float(long),
                'return_hub_cookies': False,
                'contact_zipcode': str(zipcode),
            }
            if json_data and isinstance(json_data, dict):
                json_data = json.dumps(json_data)
                if headers and 'content-type' not in {k.lower(): v for k, v in headers.items()}:
                    headers['Content-Type'] = 'application/json'

            params = {
                'url': 'https://www.bigbasket.com/member-svc/v2/member/current-delivery-address/',
                'apikey': os.getenv('ZENROWS_API_KEY'),
                'custom_headers': 'true',
                'session_id': str(session_id)
            }
            
            response = requests.put(
                    'https://api.zenrows.com/v1/', 
                    params=params,
                    headers=headers,
                    data=json_data 
                )
            log_debug(dict(response.headers), "BigBasket Cookies")
            if 'Zr-Cookies' in dict(response.headers):
                cookies.update(parse_cookies(dict(response.headers)['Zr-Cookies']))
                
                
            log_debug("Address updated successfully", "BigBasket")
            log_debug(json_data, "Address_Data")
            return headers, cookies
            
        except Exception as e:
            log_debug(f"Failed to update address: {str(e)}", "BigBasket", "ERROR")
    return False

def get_address_info_varifiers(cookies, headers, session_id):
    for i in range(3):
        try:
            headers = {
                'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
                'upgrade-insecure-requests': '1',
                'Cookie': dict_to_cookie_string(cookies),
            }
            headers.update(headers)

            params = {
                'url': 'https://www.bigbasket.com/',
                'apikey': os.getenv('ZENROWS_API_KEY'),
                'custom_headers': 'true',
                'session_id': str(session_id)
            }
            
            response = requests.get(
                    'https://api.zenrows.com/v1/', 
                    params=params,
                    headers=headers
                )
            auth_key = response.text.split(',"buildId":"')[-1].split('",')[0]
            
            if 'Zr-Cookies' in dict(response.headers):
                cookies.update(parse_cookies(dict(response.headers)['Zr-Cookies']))
                log_debug(cookies, "BigBasket Cookies")
                
            log_debug(parse_cookies(dict(response.headers)['Zr-Cookies']), "BigBasket address info")
            return headers, cookies, auth_key
            
        except Exception as e:
            log_debug(f"Failed to verify address: {str(e)}", "BigBasket", "ERROR")
    return False

def fetch_csurf_token(cookies, headers, session_id):
    for i in range(3):
        try:
            headers = {
                'accept': '*/*',
                'content-type': 'application/json',
                'x-channel': 'BB-WEB',
                'x-tracker': str(uuid.uuid4()),
                'Cookie': dict_to_cookie_string(cookies),
            }
            headers.update(headers)

            params = {
                '_': str(int(time.time() * 1000)),
                'send_address_set_by_user': 'true',
            }

            url_parts = list(urllib.parse.urlparse('https://www.bigbasket.com/ui-svc/v2/header'))
            query = dict(urllib.parse.parse_qsl(url_parts[4]))
            query.update(params)
            url_parts[4] = urllib.parse.urlencode(query)
            url = urllib.parse.urlunparse(url_parts)

            params = {
                'url': url,
                'apikey': os.getenv('ZENROWS_API_KEY'),
                'custom_headers': 'true',
                'session_id': str(session_id)
            }
            
            response = requests.get(
                    'https://api.zenrows.com/v1/', 
                    params=params,
                    headers=headers
                )
            
            cookies.update(parse_cookies(dict(response.headers)['Zr-Cookies']))
            log_debug("CSRF token fetched successfully", "BigBasket")
            return headers, cookies
            
        except Exception as e:
            log_debug(f"Failed to fetch CSRF token: {str(e)}", "BigBasket", "ERROR")
    return False

def get_initial_cookies(headers, session_id):
    for i in range(3):
        # Initial connection
        url = "https://www.bigbasket.com/"
        params = {
            'url': url,
            'apikey': os.getenv('ZENROWS_API_KEY'),
            'custom_headers': 'true',
            'session_id': str(session_id)
        }

        response = requests.get(
                    'https://api.zenrows.com/v1/', 
                    params=params,
                    headers=headers
                )
        
        log_debug(response.headers, "BigBasket Headers")

        if 'Zr-Cookies' in dict(response.headers):
            cookies = parse_cookies(dict(response.headers)['Zr-Cookies'])
            log_debug("Initial connection established", "BigBasket")
            return cookies
    return {}


def get_Bigbasket_Credentials(location_data):
    # base declarations
    headers = {
            'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
            'accept-language': 'en-US,en;q=0.9',
            'priority': 'u=0, i',
            'sec-ch-ua': '"Chromium";v="134", "Not:A-Brand";v="24", "Microsoft Edge";v="134"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
            'sec-fetch-dest': 'document',
            'sec-fetch-mode': 'navigate',
            'sec-fetch-site': 'none',
            'sec-fetch-user': '?1',
            'upgrade-insecure-requests': '1',
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0',
        }
    session_id = "".join([random.choice('123456789') for i in range(5)])

    cookies = get_initial_cookies(headers, session_id)


    xx = fetch_csurf_token(cookies, headers, session_id)
    if xx != False:
        h,c = xx
        headers.update(h)
        cookies.update(c)
    else:
        raise Exception("Failed to fetch CSRF token")
    
    xx = update_address_in_session(location_data, cookies, headers, session_id)
    if xx != False:
        h,c = xx
        headers.update(h)
        cookies.update(c)
    else:
        raise Exception("Failed to update address")

    xx = get_address_info_varifiers(cookies, headers, session_id)
    if xx != False:
        h,c,a = xx
        headers.update(h)
        cookies.update(c)
    else:
        log_debug(xx)
        raise Exception("Failed to verify address")

    log_debug("Session initialized successfully", "BigBasket", "INFO")

    data = {}
    data['BigBasket'] = {
        'auth_string': dict_to_cookie_string(cookies),
        'lat': location_data['results'][0]['geometry']['location']['lat'],
        'lon': location_data['results'][0]['geometry']['location']['lng'],
        'headers': headers,
        "auth_key": a
    }
    return data
        
def format_bigbasket_data(data):
    final_data = {'data': {}, 'credentials': data['credentials']}
    results = []
    products = data["data"]["pageProps"]["SSRData"]["tabs"][0]["product_info"]["products"]
    
    for product in products:
        if product["availability"]["avail_status"] == "001":
            result = {
                "platform": "bigbasket",
                "name": product["desc"],
                "price": product["pricing"]["discount"]["prim_price"]["sp"],
                "image_url": product["images"][0]["s"],
                "product_url": f"https://www.bigbasket.com{product['absolute_url']}",
                "quantity": product["w"]
            }
            results.append(result)
        
        for child in product.get("children", []):
            if child["availability"]["avail_status"] == "001":
                result = {
                    "platform": "bigbasket",
                    "name": child["desc"],
                    "price": child["pricing"]["discount"]["prim_price"]["sp"],
                    "image_url": child["images"][0]["s"],
                    "product_url": f"https://www.bigbasket.com{child['absolute_url']}",
                    "quantity": child["w"]
                }
                results.append(result)
        final_data['data'] = results
    return final_data

def search_bigbasket(item_name, location_data, credentials = None):

    credentials = get_Bigbasket_Credentials(location_data) if credentials is None else credentials


    for i in range(3):
        try:

            data = credentials['BigBasket']
            auth_string = data['auth_string']
            headers = data['headers']
            auth_key = data['auth_key']

            new_headers = {
                'accept': '*/*',
                'priority': 'u=1, i',
                'x-nextjs-data': '1',
                'Cookie': auth_string,
            }
            headers.update(new_headers)

            params = {
                'url': f'https://www.bigbasket.com/_next/data/{auth_key}/ps.json?q={urllib.parse.quote(item_name)}&nc=as&listing=ps',
                'apikey': os.getenv('ZENROWS_API_KEY', ''),
                'custom_headers': 'true',
            }
            
            response = requests.get(
                'https://api.zenrows.com/v1/',
                headers=headers,
                params=params,
            )
            log_debug(response.status_code, "BigBasket_status")
            if response.status_code == 404:
                return {"data": {}, "credentials": {}}
            return format_bigbasket_data({"data": response.json(), "credentials": credentials})
        
        except requests.RequestException as e:
            log_debug(f"Failed to search BigBasket: {str(e)}, Retrying...", "BigBasket", "ERROR")
            credentials = get_Bigbasket_Credentials(location_data)

    return {"data":{}, "credentials": {}}